// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMtDNXBpuy3gC24QSvDo6yDG7FIMK99po',
    appId: '1:931675840758:web:7c21bc0682aad1ef264cd7',
    messagingSenderId: '931675840758',
    projectId: 'creativa-7e9cd',
    authDomain: 'creativa-7e9cd.firebaseapp.com',
    storageBucket: 'creativa-7e9cd.appspot.com',
    measurementId: 'G-9VLSLQDK8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8cr_fP8jlhiQrfiOlO70cqwDQubVuV-k',
    appId: '1:931675840758:android:7d31dc24512cccf1264cd7',
    messagingSenderId: '931675840758',
    projectId: 'creativa-7e9cd',
    storageBucket: 'creativa-7e9cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEEKauIai5ZWqJhuji_PfE91eFoXsQzhE',
    appId: '1:931675840758:ios:61f0c902cd2f7721264cd7',
    messagingSenderId: '931675840758',
    projectId: 'creativa-7e9cd',
    storageBucket: 'creativa-7e9cd.appspot.com',
    iosBundleId: 'com.example.projectone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEEKauIai5ZWqJhuji_PfE91eFoXsQzhE',
    appId: '1:931675840758:ios:c4bdc1ed8030bd6a264cd7',
    messagingSenderId: '931675840758',
    projectId: 'creativa-7e9cd',
    storageBucket: 'creativa-7e9cd.appspot.com',
    iosBundleId: 'com.example.projectone.RunnerTests',
  );
}
